# Generated by Django 4.2.30 on 2026-08-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_menuitem_image_alter_menuitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='attendance_prompt_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='attendance_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='attendance_response',
            field=models.CharField(blank=True, choices=[('yes', 'Yes, arrived'), ('no', 'Not coming')], default='', max_length=10),
        ),
    ]
