# Generated by Django 4.2.30 on 2026-08-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('verification_pending', 'Verification Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='unpaid', max_length=25),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
