# Generated by Django 4.2.30 on 2026-08-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_payment_status_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending Verification'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='unpaid', max_length=25),
        ),
    ]
